In [237]:
import numpy as np

****ARRAY OPERATIONS****

*Arithmetic operations*

In [238]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [239]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [240]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [241]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [242]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [243]:
a1 // a2

array([0, 0, 0, 0, 0])

In [244]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

*Broadcasting*

In [245]:
l = [10,20,30,40]
arr = np.array(l)

In [246]:
arr + 10

array([20, 30, 40, 50])

In [247]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [248]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep and Shallow copy*

In [249]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [250]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [251]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [252]:
a[4:6] *10

array([50, 60])

In [253]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [254]:
a
b = a.copy()

In [255]:
b[0] = 99

In [256]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [257]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix operations*

In [258]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [259]:
A

array([[1, 2],
       [3, 4]])

In [260]:
B

array([[5, 6],
       [7, 8]])

In [261]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [262]:
A

array([[1, 2],
       [3, 4]])

In [263]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

*Stacking Array*

In [264]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [265]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [266]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [267]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting array*

In [268]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [269]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [270]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 3d Martix operation

In [271]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [272]:
arr3.shape  # 2 layers, 2 rows of each layers, 3 coloumns of each layers

(2, 2, 3)

In [273]:
print(arr3[0, 0, 0])

1


In [274]:
print(arr3[1, 1, 2])

12


In [275]:
print(arr3[0])

[[1 2 3]
 [4 5 6]]


In [276]:
print(arr3[1])

[[ 7  8  9]
 [10 11 12]]


In [277]:
print(arr3[0, 0])

[1 2 3]


In [278]:
print(arr3[1, 1])

[10 11 12]


In [279]:
print(arr3[0, :, 0])

[1 4]


In [280]:
print(arr3[1, :, 2])

[ 9 12]


In [281]:
print(arr3[:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [282]:
print(arr3[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [283]:
print(arr3[:, 1, :])

[[ 4  5  6]
 [10 11 12]]


In [284]:
print(arr3[:, :, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [285]:
print(arr3[:, :, 1:])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [286]:
print(arr3[-1])

[[ 7  8  9]
 [10 11 12]]


In [287]:
print(arr3[-1, -1])

[10 11 12]


In [288]:
print(arr3[-1, -1, -1])

12


In [289]:
print(arr3[:, ::1, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [290]:
print(arr3[::-1])

[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [291]:
print(arr3[:, :, ::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


In [292]:
print(arr3[0, :, 0:2])

[[1 2]
 [4 5]]


In [293]:
print(arr3[:, 1, 1:])

[[ 5  6]
 [11 12]]


In [294]:
print(arr3[arr3 > 5])

[ 6  7  8  9 10 11 12]


In [298]:
arr3[arr3 < 5] = 0

print(arr3)

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [299]:
print(arr3[[0, 1]])

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [300]:
print(arr3[:, [0]])

[[[0 0 0]]

 [[7 8 9]]]
