In [362]:
import numpy as np

****ARRAY OPERATIONS****

*Arithmetic operations*

In [363]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [364]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [365]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [366]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [367]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [368]:
a1 // a2

array([0, 0, 0, 0, 0])

In [369]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

*Broadcasting*

In [370]:
l = [10,20,30,40]
arr = np.array(l)

In [371]:
arr + 10

array([20, 30, 40, 50])

In [372]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [373]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep and Shallow copy*

In [374]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [375]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [376]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [377]:
a[4:6] *10

array([50, 60])

In [378]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [379]:
a
b = a.copy()

In [380]:
b[0] = 99

In [381]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [382]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix operations*

In [383]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [384]:
A

array([[1, 2],
       [3, 4]])

In [385]:
B

array([[5, 6],
       [7, 8]])

In [386]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [387]:
A

array([[1, 2],
       [3, 4]])

In [388]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

*Stacking Array*

In [389]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [390]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [391]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [392]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting array*

In [393]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [394]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [395]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 3d Martix operation

In [396]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [397]:
arr3.shape  # 2 layers, 2 rows of each layers, 3 coloumns of each layers

(2, 2, 3)

In [398]:
print(arr3[0, 0, 0])

1


In [399]:
print(arr3[1, 1, 2])

12


In [400]:
print(arr3[0])

[[1 2 3]
 [4 5 6]]


In [401]:
print(arr3[1])

[[ 7  8  9]
 [10 11 12]]


In [402]:
print(arr3[0, 0])

[1 2 3]


In [403]:
print(arr3[1, 1])

[10 11 12]


In [404]:
print(arr3[0, :, 0])

[1 4]


In [405]:
print(arr3[1, :, 2])

[ 9 12]


In [406]:
print(arr3[:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [407]:
print(arr3[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [408]:
print(arr3[:, 1, :])

[[ 4  5  6]
 [10 11 12]]


In [409]:
print(arr3[:, :, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [410]:
print(arr3[:, :, 1:])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [411]:
print(arr3[-1])

[[ 7  8  9]
 [10 11 12]]


In [412]:
print(arr3[-1, -1])

[10 11 12]


In [413]:
print(arr3[-1, -1, -1])

12


In [414]:
print(arr3[:, ::1, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [415]:
print(arr3[::-1])

[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [416]:
print(arr3[:, :, ::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


In [417]:
print(arr3[0, :, 0:2])

[[1 2]
 [4 5]]


In [418]:
print(arr3[:, 1, 1:])

[[ 5  6]
 [11 12]]


In [419]:
print(arr3[arr3 > 5])

[ 6  7  8  9 10 11 12]


In [420]:
arr3[arr3 < 5] = 0

print(arr3)

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [421]:
print(arr3[[0, 1]])

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [422]:
print(arr3[:, [0]])

[[[0 0 0]]

 [[7 8 9]]]
