In [1]:
import numpy as np

****ARRAY OPERATIONS****

*Arithmetic operations*

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

*Broadcasting*

In [9]:
l = [10,20,30,40]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 40, 50])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep and Shallow copy*

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a[4:6] *10

array([50, 60])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a
b = a.copy()

In [19]:
b[0] = 99

In [20]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix operations*

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

*Stacking Array*

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [29]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting array*

In [32]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [34]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 3d Martix operation

In [35]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [36]:
arr3.shape  # 2 layers, 2 rows of each layers, 3 coloumns of each layers

(2, 2, 3)

In [37]:
print(arr3[0, 0, 0])

1


In [38]:
print(arr3[1, 1, 2])

12


In [39]:
print(arr3[0])

[[1 2 3]
 [4 5 6]]


In [40]:
print(arr3[1])

[[ 7  8  9]
 [10 11 12]]


In [41]:
print(arr3[0, 0])

[1 2 3]


In [42]:
print(arr3[1, 1])

[10 11 12]


In [43]:
print(arr3[0, :, 0])

[1 4]


In [44]:
print(arr3[1, :, 2])

[ 9 12]


In [45]:
print(arr3[:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
print(arr3[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [47]:
print(arr3[:, 1, :])

[[ 4  5  6]
 [10 11 12]]


In [48]:
print(arr3[:, :, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [49]:
print(arr3[:, :, 1:])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [50]:
print(arr3[-1])

[[ 7  8  9]
 [10 11 12]]


In [51]:
print(arr3[-1, -1])

[10 11 12]


In [52]:
print(arr3[-1, -1, -1])

12


In [53]:
print(arr3[:, ::1, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [54]:
print(arr3[::-1])

[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [55]:
print(arr3[:, :, ::-1])

[[[ 3  2  1]
  [ 6  5  4]]

 [[ 9  8  7]
  [12 11 10]]]


In [56]:
print(arr3[0, :, 0:2])

[[1 2]
 [4 5]]


In [57]:
print(arr3[:, 1, 1:])

[[ 5  6]
 [11 12]]


In [58]:
print(arr3[arr3 > 5])

[ 6  7  8  9 10 11 12]


In [59]:
arr3[arr3 < 5] = 0

print(arr3)

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [60]:
print(arr3[[0, 1]])

[[[ 0  0  0]
  [ 0  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [61]:
print(arr3[:, [0]])

[[[0 0 0]]

 [[7 8 9]]]
