In [2]:
import numpy as np

**Valid Sudoku**

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [4]:


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [5]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [6]:
#Find the average age of students.
data[:,0].mean()

np.float64(18.4)

In [7]:
#Extract Math marks of all students.
data[:,1]


array([85, 92, 76, 65, 90])

In [8]:
#Find the highest Science mark.
data[:,2].max()

np.int64(95)

In [9]:
#Get details of the student who scored more than 90 in Math.
for i in data:
  if i[1] > 90:
    print(i)

[19 92 88]


In [10]:
#Increase Math marks of all students by 5.
data1 = data.copy()
data1 = data1[:,1] + 5
data1

array([90, 97, 81, 70, 95])

In [11]:
#Find how many students are younger than 19.
data[data[:,0] < 19].shape[0]

3

In [18]:
#Calculate the average marks in each subject (column-wise mean).
print(f"Mean of math {data[1:, 1].mean()}")
print(f"Mean of Science {data[1:, 2].mean()}")


Mean of math 80.75
Mean of Science 84.5


In [19]:
#Get data of students who scored at least 80 in both subjects.
for i in data:
  if i[1] >= 80 and i[2] >= 80:
    print(i)

[19 92 88]
[20 90 85]


In [36]:
#Replace all Science marks < 75 with 0.
data2 = data.copy()
data2[data2[:,2] < 75, 3] = 0
data2

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18,  0, 70],
       [20, 90, 85]])